name = "pureflow-leads"
main = "index.js"
compatibility_date = "2026-07-22"
workers_dev = true

[[kv_namespaces]]
binding = "LEADS"
id = "1836f6a15b9a4acbb7683d0807772ef9"

[vars]
LEAD_TO_EMAIL = "support@pureflowut.com"
LEAD_FROM_EMAIL = "PureFlow Leads <leads@pureflowut.com>"
